### ISSUE TITLE
Adopt Greenkeeper 

### ISSUE THREAD

**Issue by thousand** [linkedinlabs/icon-magic#27]
Would be good to investigate using [greenkeeper](https://greenkeeper.io/) or something similar to keep dependencies up to date automatically.

**Comment by thousand** [comment]
@amiller-gh i see that `greenkeeper` is used in the @linkedin org, do you have any idea if it's available for @linkedinlabs?

**Comment by amiller-gh** [comment]
Not sure! @chriseppstein would be able to enable it for you if no. I don’t believe I have admin access to linkedinlabs.

**Comment by oa495** [comment]
We've added `Dependabot` after @chriseppstein recommendation. https://dependabot.com/blog/hello-github/
